// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'map_test.dart' as map_test;
import 'set_test.dart' as set_test;

void main() {
  set_test.main();
  map_test.main();
}
